name: Test

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            # Install dependencies
            - run: yarn
            # Tests
            - run: yarn check:tsc
            - run: yarn check:svelte
            - run: yarn test
            - run: yarn build
