name: Test

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            # Install dependencies
            - run: npm install
            # Tests
            - run: npm run check:tsc
            - run: npm run check:svelte
            - run: npm run test:unit
            - run: npm run build
